import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { AuthProvider } from "@/context/auth-context";
import { getSession } from "@/lib/auth";
import { CartProvider } from "@/context/cart-context";
import { getInitialCart } from "@/lib/cart";
import { ToastProvider } from "@/context/toast-context";
import { ToastContainer } from "@/components/UI/toast";
import { CartDrawer } from "@/components/cart/cart-drawer";
import { Navbar } from "@/components/UI/navbar";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  // Server-side: baca session dan cart sekali di root layout
  const [user, initialCart] = await Promise.all([
    getSession(),
    getInitialCart(),
  ]);

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <ToastProvider>
          <AuthProvider initialUser={user}>
            <CartProvider initialCart={initialCart}>
              <Navbar />

              <main className="p-4">{children}</main>
              <CartDrawer />
              {modal}
              <ToastContainer />
            </CartProvider>
          </AuthProvider>
        </ToastProvider>
      </body>
    </html>
  );
}
